inherit_from: service_module/.rubocop.yml
Metrics/MethodLength:
  Exclude:
    - 'lib/argu/test_mocks.rb'
Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
  ExcludedMethods:
    - configure
    - describe
Style/MethodMissing:
  Exclude:
    - 'app/mailers/application_mailer.rb'
RSpec/LetSetup:
  Exclude:
    - 'spec/requests/create_email_tracking_event_spec.rb'
RSpec/ExampleLength:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
