inherit_from: service_module/.rubocop.yml
Metrics/MethodLength:
  Exclude:
    - 'lib/argu/test_mocks.rb'
    - 'spec/requests/index_emails_spec.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/models/collection.rb'
    - 'test/events/token_create_test.rb'
Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
    - 'spec/requests/create_email_tracking_event_spec.rb'
    - 'spec/requests/index_emails_spec.rb'
    - 'test/events/user_update_test.rb'
    - 'test/events/token_create_test.rb'
Style/MethodMissing:
  Exclude:
    - 'app/mailers/application_mailer.rb'
