inherit_from: service_module/.rubocop.yml
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
Metrics/BlockLength:
  Exclude:
    - 'config/environments/development.rb'
  ExcludedMethods:
    - configure
    - describe
RSpec/LetSetup:
  Exclude:
    - 'spec/requests/create_email_tracking_event_spec.rb'
RSpec/ExampleLength:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
