build:
  version: 2016-03-14
  steps:
    email_service:
      name: argu/email_service
      dockerfile: Dockerfile
      secrets:
        id_rsa:
          type: file
          value: _env(HOME)/.ssh/deploy_key

