development: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  secret_token: <%= ENV['SECRET_TOKEN'] %>
  mailgun_api_token: <%= ENV['MAILGUN_API_TOKEN'] %>
  mailgun_domain: <%= ENV['MAILGUN_DOMAIN'] %>
  mailgun_sender: <%= ENV['MAILGUN_SENDER'] %>
  aws_id: <%= ENV['AWS_ID'] %>
  aws_key: <%= ENV['AWS_KEY'] %>
test:
  <<: *default
production:
  <<: *default
staging:
  <<: *default
